server:
  host: 127.0.0.1
  port: 8000

reshare:
  enable: true
  ignore:
  - 123
  interval: 300
  errorretry: 43200

baidu:
  cookie: 


notify:
  enable: true
  cron: "0 0 21 * * ? *"
  sct: 
    enable: true
    key: 
    channel: 9 
  push-plus:
    enable: true
    token: 
    channel: wechat 